std_msgs/Header      header

string[] 	        device_serial_number                    #Serialnumbers of the devices of signal origin
float32[]           prediction_probablility      #Probability of prediction's according to classifier
string[]            glossary                     #possibilities linked to the prediction_probability with same index   

string[]            model_type                  #Machine learning model type
string[]            model_version               #The version the model is trained with/ From what data was the model created 
