# Form implementation generated from reading ui file 'resource/form.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RHDashboard(object):
    def setupUi(self, RHDashboard):
        RHDashboard.setObjectName("RHDashboard")
        RHDashboard.resize(1920, 1080)
        RHDashboard.setStyleSheet("#RHDashboard {\n"
"    background: qradialgradient( cx:0.5 cy:0.5, radius:0.8 fx:0.5, fy:0.5, stop:0 #0e79a5, stop:1 black);\n"
"}\n"
"\n"
"* {\n"
"    color: white;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(RHDashboard)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(parent=RHDashboard)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 3px solid white;\n"
"    border-radius: 20px;\n"
"    margin: 20px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ADLIconLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.ADLIconLabel.setMinimumSize(QtCore.QSize(120, 120))
        self.ADLIconLabel.setObjectName("ADLIconLabel")
        self.horizontalLayout_2.addWidget(self.ADLIconLabel)
        self.ADLTitleLabel = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.ADLTitleLabel.setFont(font)
        self.ADLTitleLabel.setObjectName("ADLTitleLabel")
        self.horizontalLayout_2.addWidget(self.ADLTitleLabel)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.WheelchairImage = QtWidgets.QLabel(parent=self.groupBox)
        self.WheelchairImage.setText("")
        self.WheelchairImage.setPixmap(QtGui.QPixmap("resource/side-graphics.png"))
        self.WheelchairImage.setObjectName("WheelchairImage")
        self.verticalLayout.addWidget(self.WheelchairImage)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.ADLLayout = QtWidgets.QVBoxLayout()
        self.ADLLayout.setContentsMargins(20, -1, 80, -1)
        self.ADLLayout.setObjectName("ADLLayout")
        self.horizontalLayout.addLayout(self.ADLLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=RHDashboard)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resource/heart-signal.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.hrLabel = QtWidgets.QLabel(parent=RHDashboard)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.hrLabel.setFont(font)
        self.hrLabel.setStyleSheet("* {\n"
"            font-size: 2em;\n"
"          }")
        self.hrLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hrLabel.setObjectName("hrLabel")
        self.horizontalLayout_3.addWidget(self.hrLabel)
        self.rrLabel = QtWidgets.QLabel(parent=RHDashboard)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.rrLabel.setFont(font)
        self.rrLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rrLabel.setObjectName("rrLabel")
        self.horizontalLayout_3.addWidget(self.rrLabel)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.rightLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.rightLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(3, 4)
        self.horizontalLayout.setStretch(4, 1)

        self.retranslateUi(RHDashboard)
        QtCore.QMetaObject.connectSlotsByName(RHDashboard)

    def retranslateUi(self, RHDashboard):
        _translate = QtCore.QCoreApplication.translate
        RHDashboard.setWindowTitle(_translate("RHDashboard", "RHDashboard"))
        self.ADLIconLabel.setText(_translate("RHDashboard", "Icon"))
        self.ADLTitleLabel.setText(_translate("RHDashboard", "Title"))
        self.hrLabel.setText(_translate("RHDashboard", "HeartRate"))
        self.rrLabel.setText(_translate("RHDashboard", "RespiratoryRate"))
