# Example configuration parameters for the ROS2 healthcare system


mbient_ros:
  ros__parameters:
    mac_add: "F1:1F:CC:0E:65:86"
sensomative_ros:
  ros__parameters:
    mac_add: "CC:CC:CC:0A:39:C7"

